### ISSUE TITLE
Publishing a new minor version

### ISSUE THREAD

**Issue by petrochenkov** [couchdb-rs/couchdb#57]
Hi.
https://github.com/rust-lang/rust/pull/42125 is going to turn some old compatibility "private-in-public" warnings in `rustc` into hard errors.
`crates.io` testing discovered that published version of this crate is affected by one of those errors.
The problem seems to be fixed on the current master, could you push it on crates.io as `couchdb-0.5.2`?
(Even if the crate is deprecated, it would still be useful for the compiler's regression testing.)

**Comment by cmbrandenburg** [comment]
Resolved in #58.

**Comment by petrochenkov** [comment]
Thanks!
